destinations:
  metric-store:
    type: prometheus
    url: http://prometheus-server.prometheus.svc:9090/api/v1/write
    metricEnrichment:
      podLabels:
        - color
      namespaceLabels:
        - team
collectors:
  alloy-metrics:
    presets:
      - clustered
      - statefulset
    includeDestinations:
      - metric-store
    alloy:
      stabilityLevel: experimental
clusterMetrics:
  enabled: true
  collector: alloy-metrics
telemetryServices:
  kube-state-metrics:
    deploy: true
cluster:
  name: metric-enrichment-test-cluster

