destinations:
  prometheus:
    type: prometheus
    url: http://prometheus.prometheus.svc:9090/api/v1/write
collectors:
  alloy-metrics:
    presets:
      - clustered
      - statefulset
cluster:
  name: cert-manager-integration-cluster
integrations:
  cert-manager:
    instances:
      - name: cert-manager
        labelSelectors:
          app.kubernetes.io/name: cert-manager
  collector: alloy-metrics

