destinations:
  prometheus:
    type: prometheus
    url: http://prometheus.prometheus.svc:9090/api/v1/write
collectors:
  alloy-metrics:
    presets:
      - clustered
      - statefulset
clusterMetrics:
  enabled: true
  collector: alloy-metrics
telemetryServices:
  kube-state-metrics:
    deploy: true
    autosharding:
      enabled: true
    replicas: 5
cluster:
  name: sharded-kube-state-metrics

