destinations:
  prometheus:
    type: prometheus
    url: http://prometheus.prometheus.svc:9090/api/v1/write
collectors:
  alloy-metrics:
    presets:
      - clustered
      - statefulset
clusterMetrics:
  enabled: true
  collector: alloy-metrics
telemetryServices:
  kepler:
    deploy: true
  opencost:
    deploy: true
    metricsSource: prometheus
    opencost:
      exporter:
        defaultClusterId: cluster-metrics-example-cluster
      prometheus:
        external:
          url: http://prometheus.prometheus.svc:9090/api/v1/query
  kube-state-metrics:
    deploy: true
costMetrics:
  enabled: true
  collector: alloy-metrics
hostMetrics:
  energyMetrics:
    enabled: true
  enabled: true
  collector: alloy-metrics
cluster:
  name: cluster-metrics-example-cluster

