destinations:
  metricsService:
    type: prometheus
    url: https://prometheus.example.com/api/prom/push
    auth:
      type: basic
      username: 12345
      password: It's a secret to everyone
  logsService:
    type: loki
    url: https://loki.example.com/loki/api/v1/push
    auth:
      type: basic
      username: 12345
      password: It's a secret to everyone
collectors:
  alloy-metrics:
    presets:
      - clustered
      - statefulset
    alloy:
      resources:
        requests:
          cpu: 1m
          memory: 500Mi
      storagePath: /var/lib/alloy
      mounts:
        extra:
          - name: alloy-wal
            mountPath: /var/lib/alloy
    controller:
      autoscaling:
        enabled: true
        minReplicas: 2
        maxReplicas: 10
        targetCPUUtilizationPercentage: 0
        targetMemoryUtilizationPercentage: 80
      enableStatefulSetAutoDeletePVC: true
      volumeClaimTemplates:
        - metadata:
            name: alloy-wal
          spec:
            accessModes:
              - ReadWriteOnce
            storageClassName: standard
            resources:
              requests:
                storage: 5Gi
  alloy-logs:
    presets:
      - filesystem-log-reader
      - daemonset
    alloy:
      storagePath: /var/lib/alloy
      mounts:
        extra:
          - name: alloy-log-positions
            mountPath: /var/lib/alloy
    controller:
      volumes:
        extra:
          - name: alloy-log-positions
            hostPath:
              path: /var/alloy-log-storage
              type: DirectoryOrCreate
  alloy-singleton:
    presets:
      - singleton
clusterMetrics:
  enabled: true
  collector: alloy-metrics
telemetryServices:
  kube-state-metrics:
    deploy: true
cluster:
  name: alloy-autoscaling-and-storage-test
clusterEvents:
  enabled: true
  collector: alloy-singleton
podLogsViaLoki:
  enabled: true
  collector: alloy-logs
annotationAutodiscovery:
  enabled: true
  collector: alloy-metrics
prometheusOperatorObjects:
  enabled: true
  crds:
    deploy: true
  collector: alloy-metrics
integrations:
  alloy:
    instances:
      - name: alloy
        labelSelectors:
          app.kubernetes.io/name:
            - alloy-metrics
            - alloy-singleton
            - alloy-logs
        metrics:
          tuning:
            useDefaultAllowList: false
            includeMetrics:
              - alloy_build_info
  collector: alloy-metrics

