destinations:
  prometheus:
    type: prometheus
    url: http://prometheus.prometheus.svc:9090/api/v1/write
collectors:
  alloy-metrics:
    presets:
      - clustered
      - statefulset
    fullnameOverride: metric-collector
clusterMetrics:
  enabled: true
  collector: alloy-metrics
telemetryServices:
  node-exporter:
    deploy: true
    fullnameOverride: node-metric-source
  kepler:
    deploy: true
    fullnameOverride: energy-metric-source
  opencost:
    deploy: true
    fullnameOverride: cost-metric-source
    metricsSource: prometheus
    opencost:
      exporter:
        defaultClusterId: fullname-override-test
      prometheus:
        external:
          url: http://prometheus.prometheus.svc:9090/api/v1/query
  kube-state-metrics:
    deploy: true
costMetrics:
  enabled: true
  collector: alloy-metrics
hostMetrics:
  linuxHosts:
    enabled: true
    labelMatchers:
      app.kubernetes.io/name: node-metric-source
  energyMetrics:
    enabled: true
  enabled: true
  collector: alloy-metrics
cluster:
  name: fullname-override-test

